<?php

JurisdictionModel::addSqlQuery('COUNTRY_LIST', 'SELECT * FROM JURISDICTION ORDER BY JURISDICTION_COUNTRY');

JurisdictionModel::addSqlQuery('SERVICE_LIST', 'SELECT SERVICE_NAME FROM SERVICES ORDER BY SERVICE_NAME');

JurisdictionModel::addSqlQuery('DEPARTMENT_LIST', 'SELECT * FROM DEPARTMENT ORDER BY DEPARTMENT_NUMBER');

JurisdictionModel::addSqlQuery('DEPARTMENTS_GET_WITH_COUNTRY', 'SELECT * FROM DEPARTMENT WHERE DEPARTMENT_COUNTRY=:country ORDER BY DEPARTMENT_NUMBER');

?>
