<?php

UserModel::addSqlQuery('USER_CREATE',
'INSERT INTO USER ( USER_LOGIN, USER_PWD, USER_EMAIL, USER_NAME, USER_SURNAME, USER_SERVICE, USER_COUNTRY) VALUES (:login,:pwd,:email,:name,:surname,:service,:country)');

UserModel::addSqlQuery('USER_CONNECT','SELECT * FROM USER WHERE USER_LOGIN=:login and USER_PWD=:password');

UserModel::addSqlQuery('USER_GET_ID_WITH_LOGIN', 'SELECT USER_ID FROM USER WHERE USER_LOGIN=:login');

UserModel::addSqlQuery('USER_ATTRIBUTE_LOCATION',
'INSERT INTO USER_LOCATION (USER_ID,USER_DEPARTMENT_NAME,USER_DEPARTMENT_NUMBER,USER_TOWN,USER_POSTCODE) VALUES (:user_id,"",0,"",0)');

UserModel::addSqlQuery('USER_CREATE_LOCATION',
'UPDATE USER_LOCATION SET USER_DEPARTMENT_NAME=:department_name,USER_TOWN=:town,USER_POSTCODE=:postcode WHERE USER_ID =:user_id');
//,USER_DEPARTMENT_NUMBER=department_number

UserModel::addSqlQuery('USER_LIST', 'SELECT * FROM USER ORDER BY USER_LOGIN');

UserModel::addSqlQuery('GET_LOCATION_WITH_USER_ID', 'SELECT * FROM USER_LOCATION WHERE USER_ID=:user_id');

UserModel::addSqlQuery('USER_GET_WITH_EMAIL', 'SELECT * FROM USER WHERE USER_EMAIL=:email');

UserModel::addSqlQuery('USER_GET_WITH_LOGIN', 'SELECT * FROM USER WHERE USER_LOGIN=:login');

UserModel::addSqlQuery('USER_GET_WITH_ID', 'SELECT * FROM USER WHERE USER_ID=:id');

UserModel::addSqlQuery('USER_GET_WITH_PWD', 'SELECT * FROM USER WHERE USER_PWD=:pwd');

UserModel::addSqlQuery('USER_CHANGE_LOGIN', 'UPDATE USER SET USER_LOGIN = :newLogin WHERE USER_LOGIN = :currentLogin');

?>
